#!/usr/bin/python
import sys
import Adafruit_DHT
import json

while True:

    humidity, temperature = Adafruit_DHT.read_retry(11, 4)

    print ('Temp: {0:0.1f} C  Humidity: {1:0.1f} %'.format(temperature, humidity))
    with open("data_file.json","w") as write_file:
        json.dump(humidity,write_file) 
